//
//  CoordinateInfo+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - CoordinateInfo properties

extension CoordinateInfo {

    @NSManaged var administrativeArea_Placemark: String?
    @NSManaged var altitude: Double
    @NSManaged var ccISOcountryCode_Placemark: String?
    @NSManaged var country_Placemark: String?
    @NSManaged var course: Double // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var creationDate: Date?
    @NSManaged var customTitle: String?
    @NSManaged var favorite: Bool
    @NSManaged var hidden: Bool
    @NSManaged var horizontalAccuracy: Double
    @NSManaged var inlandWater_Placemark: String?
    @NSManaged var latitude: Double
    @NSManaged var level: Int32
    @NSManaged var locality_Placemark: String?
    @NSManaged var localizedPlaceString_Placemark: String?
    @NSManaged var longitude: Double
    @NSManaged var modificationDate: Date?
    @NSManaged var name_Placemark: String?
    @NSManaged var ocean_Placemark: String?
    @NSManaged var postalCode_Placemark: String?
    @NSManaged var reverseGeocodeFailureCount: Int16 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var reverseGeocodeSucceed: Bool
    @NSManaged var speed: Double
    @NSManaged var subAdministrativeArea_Placemark: String?
    @NSManaged var subLocality_Placemark: String?
    @NSManaged var subThoroughfare_Placemark: String?
    @NSManaged var thoroughfare_Placemark: String?
    @NSManaged var verticalAccuracy: Double

}

