//
//  FootprintsRepositoryInfo+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - FootprintsRepositoryInfo properties

extension FootprintsRepositoryInfo {

    @NSManaged var averageSpeed: Double
    @NSManaged var creationDate: Date?
    @NSManaged var distance: Double
    @NSManaged var duration: Double
    @NSManaged var endDate: Date?
    @NSManaged var footprintsCount: Int32
    @NSManaged var footprintsRepositoryType: Int16
    @NSManaged var identifier: String
    @NSManaged var modificatonDate: Date?
    @NSManaged var placemarkStatisticalInfo: String?
    @NSManaged var radius: Double
    @NSManaged var startDate: Date?
    @NSManaged var title: String?

}

