//
//  MediaInfo+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - MediaInfo properties

extension MediaInfo {

    @NSManaged var actAsThumbnail: Bool
    @NSManaged var contentType: String
    @NSManaged var creationDate: Date?
    @NSManaged var eliminateThisMedia: Bool
    @NSManaged var faceListArray: Data?
    @NSManaged var favorite: Bool
    @NSManaged var fileSize: Int64 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var identifier: String
    @NSManaged var invalid: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var mediaSourceIdentifier: String?
    @NSManaged var mediaType: Int16
    @NSManaged var modificationDate: Date?
    @NSManaged var name: String?
    @NSManaged var originalURLString: String?
    @NSManaged var thumbnailURLString: String?
    @NSManaged var urlString: String?

    @NSManaged var coordinateInfo: CoordinateInfo?

}

